# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(309, 287)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.applyButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.applyButton.sizePolicy().hasHeightForWidth())
        self.applyButton.setSizePolicy(sizePolicy)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout.addWidget(self.applyButton, 4, 1, 1, 1)
        self.generalSettingsGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generalSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.generalSettingsGroupBox.setSizePolicy(sizePolicy)
        self.generalSettingsGroupBox.setObjectName("generalSettingsGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.generalSettingsGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.idleModeLabel = QtWidgets.QLabel(self.generalSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idleModeLabel.sizePolicy().hasHeightForWidth())
        self.idleModeLabel.setSizePolicy(sizePolicy)
        self.idleModeLabel.setObjectName("idleModeLabel")
        self.gridLayout_3.addWidget(self.idleModeLabel, 0, 0, 1, 1)
        self.brightnessLabel = QtWidgets.QLabel(self.generalSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessLabel.sizePolicy().hasHeightForWidth())
        self.brightnessLabel.setSizePolicy(sizePolicy)
        self.brightnessLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.brightnessLabel.setObjectName("brightnessLabel")
        self.gridLayout_3.addWidget(self.brightnessLabel, 2, 0, 1, 1)
        self.brightnessSlider = QtWidgets.QSlider(self.generalSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessSlider.sizePolicy().hasHeightForWidth())
        self.brightnessSlider.setSizePolicy(sizePolicy)
        self.brightnessSlider.setMinimumSize(QtCore.QSize(119, 0))
        self.brightnessSlider.setMaximum(255)
        self.brightnessSlider.setProperty("value", 255)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.gridLayout_3.addWidget(self.brightnessSlider, 2, 1, 1, 1)
        self.maxBrightnessSpinBox = QtWidgets.QSpinBox(self.generalSettingsGroupBox)
        self.maxBrightnessSpinBox.setMaximum(255)
        self.maxBrightnessSpinBox.setProperty("value", 255)
        self.maxBrightnessSpinBox.setObjectName("maxBrightnessSpinBox")
        self.gridLayout_3.addWidget(self.maxBrightnessSpinBox, 2, 2, 1, 1)
        self.idleModeComboBox = QtWidgets.QComboBox(self.generalSettingsGroupBox)
        self.idleModeComboBox.setObjectName("idleModeComboBox")
        self.gridLayout_3.addWidget(self.idleModeComboBox, 0, 1, 1, 2)
        self.gridLayout.addWidget(self.generalSettingsGroupBox, 3, 0, 1, 2)
        self.controlModeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlModeGroupBox.sizePolicy().hasHeightForWidth())
        self.controlModeGroupBox.setSizePolicy(sizePolicy)
        self.controlModeGroupBox.setObjectName("controlModeGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlModeGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.controlModeLabel = QtWidgets.QLabel(self.controlModeGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlModeLabel.sizePolicy().hasHeightForWidth())
        self.controlModeLabel.setSizePolicy(sizePolicy)
        self.controlModeLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.controlModeLabel.setObjectName("controlModeLabel")
        self.gridLayout_2.addWidget(self.controlModeLabel, 0, 0, 1, 1)
        self.controlModeComboBox = QtWidgets.QComboBox(self.controlModeGroupBox)
        self.controlModeComboBox.setMinimumSize(QtCore.QSize(100, 20))
        self.controlModeComboBox.setBaseSize(QtCore.QSize(0, 0))
        self.controlModeComboBox.setObjectName("controlModeComboBox")
        self.gridLayout_2.addWidget(self.controlModeComboBox, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.controlModeGroupBox, 2, 0, 1, 2)
        self.SerialPortSettingsComboBox = QtWidgets.QGroupBox(self.centralwidget)
        self.SerialPortSettingsComboBox.setObjectName("SerialPortSettingsComboBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.SerialPortSettingsComboBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SerialPortLabel = QtWidgets.QLabel(self.SerialPortSettingsComboBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SerialPortLabel.sizePolicy().hasHeightForWidth())
        self.SerialPortLabel.setSizePolicy(sizePolicy)
        self.SerialPortLabel.setObjectName("SerialPortLabel")
        self.horizontalLayout.addWidget(self.SerialPortLabel)
        self.serialPortComboBox = QtWidgets.QComboBox(self.SerialPortSettingsComboBox)
        self.serialPortComboBox.setObjectName("serialPortComboBox")
        self.horizontalLayout.addWidget(self.serialPortComboBox)
        self.gridLayout.addWidget(self.SerialPortSettingsComboBox, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 309, 21))
        self.menubar.setObjectName("menubar")
        self.menupyLight = QtWidgets.QMenu(self.menubar)
        self.menupyLight.setObjectName("menupyLight")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menupyLight.addAction(self.actionExit)
        self.menubar.addAction(self.menupyLight.menuAction())

        self.retranslateUi(MainWindow)
        self.maxBrightnessSpinBox.valueChanged['int'].connect(self.brightnessSlider.setValue)
        self.brightnessSlider.valueChanged['int'].connect(self.maxBrightnessSpinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyLight"))
        self.applyButton.setText(_translate("MainWindow", "Apply"))
        self.generalSettingsGroupBox.setTitle(_translate("MainWindow", "General Settings"))
        self.idleModeLabel.setText(_translate("MainWindow", "Idle Mode"))
        self.brightnessLabel.setText(_translate("MainWindow", "Maximum Brightness"))
        self.controlModeGroupBox.setTitle(_translate("MainWindow", "Control Mode Settings"))
        self.controlModeLabel.setText(_translate("MainWindow", "Control Mode"))
        self.SerialPortSettingsComboBox.setTitle(_translate("MainWindow", "Serial Port Settings"))
        self.SerialPortLabel.setText(_translate("MainWindow", "Serial Port"))
        self.menupyLight.setTitle(_translate("MainWindow", "pyLight"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

